<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SidoSggCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sido_sgg_codes')->truncate();

        $codes = [
            // 전체
            ['sido_code' => '00', 'sido_name' => '전체', 'sgg_code' => '00000', 'sgg_name' => '전체'],
            // 서울특별시
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11140', 'sgg_name' => '중구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11560', 'sgg_name' => '영등포구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11230', 'sgg_name' => '동대문구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11260', 'sgg_name' => '중랑구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11380', 'sgg_name' => '은평구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11545', 'sgg_name' => '금천구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11590', 'sgg_name' => '동작구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11680', 'sgg_name' => '강남구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11110', 'sgg_name' => '종로구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11170', 'sgg_name' => '용산구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11215', 'sgg_name' => '광진구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11470', 'sgg_name' => '양천구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11410', 'sgg_name' => '서대문구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11440', 'sgg_name' => '마포구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11200', 'sgg_name' => '성동구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11305', 'sgg_name' => '강북구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11650', 'sgg_name' => '서초구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11710', 'sgg_name' => '송파구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11740', 'sgg_name' => '강동구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11290', 'sgg_name' => '성북구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11320', 'sgg_name' => '도봉구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11350', 'sgg_name' => '노원구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11500', 'sgg_name' => '강서구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11530', 'sgg_name' => '구로구'],
            ['sido_code' => '11', 'sido_name' => '서울특별시', 'sgg_code' => '11620', 'sgg_name' => '관악구'],
            // 부산광역시
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26350', 'sgg_name' => '해운대구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26140', 'sgg_name' => '서구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26500', 'sgg_name' => '수영구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26260', 'sgg_name' => '동래구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26110', 'sgg_name' => '중구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26440', 'sgg_name' => '강서구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26710', 'sgg_name' => '기장군'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26170', 'sgg_name' => '동구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26410', 'sgg_name' => '금정구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26530', 'sgg_name' => '사상구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26290', 'sgg_name' => '남구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26200', 'sgg_name' => '영도구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26470', 'sgg_name' => '연제구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26230', 'sgg_name' => '부산진구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26320', 'sgg_name' => '북구'],
            ['sido_code' => '26', 'sido_name' => '부산광역시', 'sgg_code' => '26380', 'sgg_name' => '사하구'],
            // 대구광역시
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27170', 'sgg_name' => '서구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27290', 'sgg_name' => '달서구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27200', 'sgg_name' => '남구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27720', 'sgg_name' => '군위군'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27110', 'sgg_name' => '중구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27260', 'sgg_name' => '수성구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27230', 'sgg_name' => '북구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27140', 'sgg_name' => '동구'],
            ['sido_code' => '27', 'sido_name' => '대구광역시', 'sgg_code' => '27710', 'sgg_name' => '달성군'],
            // 인천광역시
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28140', 'sgg_name' => '동구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28720', 'sgg_name' => '옹진군'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28185', 'sgg_name' => '연수구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28260', 'sgg_name' => '서구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28110', 'sgg_name' => '중구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28710', 'sgg_name' => '강화군'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28245', 'sgg_name' => '계양구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28237', 'sgg_name' => '부평구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28177', 'sgg_name' => '미추홀구'],
            ['sido_code' => '28', 'sido_name' => '인천광역시', 'sgg_code' => '28200', 'sgg_name' => '남동구'],
            // 광주광역시
            ['sido_code' => '29', 'sido_name' => '광주광역시', 'sgg_code' => '29140', 'sgg_name' => '서구'],
            ['sido_code' => '29', 'sido_name' => '광주광역시', 'sgg_code' => '29200', 'sgg_name' => '광산구'],
            ['sido_code' => '29', 'sido_name' => '광주광역시', 'sgg_code' => '29170', 'sgg_name' => '북구'],
            ['sido_code' => '29', 'sido_name' => '광주광역시', 'sgg_code' => '29155', 'sgg_name' => '남구'],
            ['sido_code' => '29', 'sido_name' => '광주광역시', 'sgg_code' => '29110', 'sgg_name' => '동구'],
            // 대전광역시
            ['sido_code' => '30', 'sido_name' => '대전광역시', 'sgg_code' => '30110', 'sgg_name' => '동구'],
            ['sido_code' => '30', 'sido_name' => '대전광역시', 'sgg_code' => '30230', 'sgg_name' => '대덕구'],
            ['sido_code' => '30', 'sido_name' => '대전광역시', 'sgg_code' => '30170', 'sgg_name' => '서구'],
            ['sido_code' => '30', 'sido_name' => '대전광역시', 'sgg_code' => '30140', 'sgg_name' => '중구'],
            ['sido_code' => '30', 'sido_name' => '대전광역시', 'sgg_code' => '30200', 'sgg_name' => '유성구'],
            // 울산광역시
            ['sido_code' => '31', 'sido_name' => '울산광역시', 'sgg_code' => '31110', 'sgg_name' => '중구'],
            ['sido_code' => '31', 'sido_name' => '울산광역시', 'sgg_code' => '31170', 'sgg_name' => '동구'],
            ['sido_code' => '31', 'sido_name' => '울산광역시', 'sgg_code' => '31710', 'sgg_name' => '울주군'],
            ['sido_code' => '31', 'sido_name' => '울산광역시', 'sgg_code' => '31140', 'sgg_name' => '남구'],
            ['sido_code' => '31', 'sido_name' => '울산광역시', 'sgg_code' => '31200', 'sgg_name' => '북구'],
            // 세종특별자치시
            ['sido_code' => '36', 'sido_name' => '세종특별자치시', 'sgg_code' => '36110', 'sgg_name' => '세종특별자치시'],
            // 경기도
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41111', 'sgg_name' => '수원시 장안구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41285', 'sgg_name' => '고양시 일산동구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41150', 'sgg_name' => '의정부시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41360', 'sgg_name' => '남양주시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41370', 'sgg_name' => '오산시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41390', 'sgg_name' => '시흥시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41461', 'sgg_name' => '용인시 처인구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41192', 'sgg_name' => '부천시 원미구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41194', 'sgg_name' => '부천시 소사구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41196', 'sgg_name' => '부천시 오정구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41110', 'sgg_name' => '수원시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41115', 'sgg_name' => '수원시 팔달구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41130', 'sgg_name' => '성남시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41135', 'sgg_name' => '성남시 분당구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41173', 'sgg_name' => '안양시 동안구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41220', 'sgg_name' => '평택시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41271', 'sgg_name' => '안산시 상록구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41281', 'sgg_name' => '고양시 덕양구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41287', 'sgg_name' => '고양시 일산서구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41310', 'sgg_name' => '구리시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41430', 'sgg_name' => '의왕시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41463', 'sgg_name' => '용인시 기흥구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41480', 'sgg_name' => '파주시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41570', 'sgg_name' => '김포시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41610', 'sgg_name' => '광주시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41650', 'sgg_name' => '포천시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41670', 'sgg_name' => '여주시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41820', 'sgg_name' => '가평군'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41550', 'sgg_name' => '안성시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41590', 'sgg_name' => '화성시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41117', 'sgg_name' => '수원시 영통구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41210', 'sgg_name' => '광명시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41273', 'sgg_name' => '안산시 단원구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41630', 'sgg_name' => '양주시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41800', 'sgg_name' => '연천군'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41250', 'sgg_name' => '동두천시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41830', 'sgg_name' => '양평군'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41170', 'sgg_name' => '안양시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41131', 'sgg_name' => '성남시 수정구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41450', 'sgg_name' => '하남시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41113', 'sgg_name' => '수원시 권선구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41290', 'sgg_name' => '과천시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41410', 'sgg_name' => '군포시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41465', 'sgg_name' => '용인시 수지구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41500', 'sgg_name' => '이천시'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41171', 'sgg_name' => '안양시 만안구'],
            ['sido_code' => '41', 'sido_name' => '경기도', 'sgg_code' => '41133', 'sgg_name' => '성남시 중원구'],
            // 충청북도
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43770', 'sgg_name' => '음성군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43800', 'sgg_name' => '단양군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43111', 'sgg_name' => '청주시 상당구'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43113', 'sgg_name' => '청주시 흥덕구'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43130', 'sgg_name' => '충주시'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43720', 'sgg_name' => '보은군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43740', 'sgg_name' => '영동군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43745', 'sgg_name' => '증평군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43760', 'sgg_name' => '괴산군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43730', 'sgg_name' => '옥천군'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43112', 'sgg_name' => '청주시 서원구'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43150', 'sgg_name' => '제천시'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43114', 'sgg_name' => '청주시 청원구'],
            ['sido_code' => '43', 'sido_name' => '충청북도', 'sgg_code' => '43750', 'sgg_name' => '진천군'],
            // 충청남도
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44131', 'sgg_name' => '천안시 동남구'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44770', 'sgg_name' => '서천군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44200', 'sgg_name' => '아산시'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44760', 'sgg_name' => '부여군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44133', 'sgg_name' => '천안시 서북구'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44150', 'sgg_name' => '공주시'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44210', 'sgg_name' => '서산시'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44250', 'sgg_name' => '계룡시'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44710', 'sgg_name' => '금산군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44790', 'sgg_name' => '청양군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44810', 'sgg_name' => '예산군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44825', 'sgg_name' => '태안군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44270', 'sgg_name' => '당진시'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44800', 'sgg_name' => '홍성군'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44180', 'sgg_name' => '보령시'],
            ['sido_code' => '44', 'sido_name' => '충청남도', 'sgg_code' => '44230', 'sgg_name' => '논산시'],
            // 전라남도
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46710', 'sgg_name' => '담양군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46720', 'sgg_name' => '곡성군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46770', 'sgg_name' => '고흥군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46800', 'sgg_name' => '장흥군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46840', 'sgg_name' => '무안군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46130', 'sgg_name' => '여수시'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46170', 'sgg_name' => '나주시'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46780', 'sgg_name' => '보성군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46790', 'sgg_name' => '화순군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46830', 'sgg_name' => '영암군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46870', 'sgg_name' => '영광군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46890', 'sgg_name' => '완도군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46900', 'sgg_name' => '진도군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46820', 'sgg_name' => '해남군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46230', 'sgg_name' => '광양시'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46910', 'sgg_name' => '신안군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46810', 'sgg_name' => '강진군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46860', 'sgg_name' => '함평군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46880', 'sgg_name' => '장성군'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46110', 'sgg_name' => '목포시'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46150', 'sgg_name' => '순천시'],
            ['sido_code' => '46', 'sido_name' => '전라남도', 'sgg_code' => '46730', 'sgg_name' => '구례군'],
            // 경상북도
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47290', 'sgg_name' => '경산시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47840', 'sgg_name' => '성주군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47111', 'sgg_name' => '포항시 남구'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47850', 'sgg_name' => '칠곡군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47830', 'sgg_name' => '고령군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47190', 'sgg_name' => '구미시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47920', 'sgg_name' => '봉화군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47110', 'sgg_name' => '포항시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47940', 'sgg_name' => '울릉군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47280', 'sgg_name' => '문경시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47170', 'sgg_name' => '안동시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47130', 'sgg_name' => '경주시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47770', 'sgg_name' => '영덕군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47760', 'sgg_name' => '영양군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47750', 'sgg_name' => '청송군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47730', 'sgg_name' => '의성군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47250', 'sgg_name' => '상주시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47230', 'sgg_name' => '영천시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47150', 'sgg_name' => '김천시'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47113', 'sgg_name' => '포항시 북구'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47930', 'sgg_name' => '울진군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47900', 'sgg_name' => '예천군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47820', 'sgg_name' => '청도군'],
            ['sido_code' => '47', 'sido_name' => '경상북도', 'sgg_code' => '47210', 'sgg_name' => '영주시'],
            // 경상남도
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48720', 'sgg_name' => '의령군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48240', 'sgg_name' => '사천시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48820', 'sgg_name' => '고성군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48129', 'sgg_name' => '창원시 진해구'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48125', 'sgg_name' => '창원시 마산합포구'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48840', 'sgg_name' => '남해군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48170', 'sgg_name' => '진주시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48120', 'sgg_name' => '창원시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48890', 'sgg_name' => '합천군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48870', 'sgg_name' => '함양군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48850', 'sgg_name' => '하동군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48740', 'sgg_name' => '창녕군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48730', 'sgg_name' => '함안군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48330', 'sgg_name' => '양산시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48310', 'sgg_name' => '거제시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48250', 'sgg_name' => '김해시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48220', 'sgg_name' => '통영시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48127', 'sgg_name' => '창원시 마산회원구'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48123', 'sgg_name' => '창원시 성산구'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48880', 'sgg_name' => '거창군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48270', 'sgg_name' => '밀양시'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48860', 'sgg_name' => '산청군'],
            ['sido_code' => '48', 'sido_name' => '경상남도', 'sgg_code' => '48121', 'sgg_name' => '창원시 의창구'],
            // 제주특별자치도
            ['sido_code' => '50', 'sido_name' => '제주특별자치도', 'sgg_code' => '50130', 'sgg_name' => '서귀포시'],
            ['sido_code' => '50', 'sido_name' => '제주특별자치도', 'sgg_code' => '50110', 'sgg_name' => '제주시'],
            // 강원특별자치도
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51150', 'sgg_name' => '강릉시'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51110', 'sgg_name' => '춘천시'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51770', 'sgg_name' => '정선군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51830', 'sgg_name' => '양양군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51820', 'sgg_name' => '고성군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51800', 'sgg_name' => '양구군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51780', 'sgg_name' => '철원군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51760', 'sgg_name' => '평창군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51720', 'sgg_name' => '홍천군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51230', 'sgg_name' => '삼척시'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51190', 'sgg_name' => '태백시'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51790', 'sgg_name' => '화천군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51750', 'sgg_name' => '영월군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51810', 'sgg_name' => '인제군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51130', 'sgg_name' => '원주시'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51170', 'sgg_name' => '동해시'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51730', 'sgg_name' => '횡성군'],
            ['sido_code' => '51', 'sido_name' => '강원특별자치도', 'sgg_code' => '51210', 'sgg_name' => '속초시'],
            // 전북특별자치도
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52770', 'sgg_name' => '순창군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52730', 'sgg_name' => '무주군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52710', 'sgg_name' => '완주군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52210', 'sgg_name' => '김제시'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52130', 'sgg_name' => '군산시'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52113', 'sgg_name' => '전주시 덕진구'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52111', 'sgg_name' => '전주시 완산구'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52750', 'sgg_name' => '임실군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52180', 'sgg_name' => '정읍시'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52790', 'sgg_name' => '고창군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52190', 'sgg_name' => '남원시'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52720', 'sgg_name' => '진안군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52800', 'sgg_name' => '부안군'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52140', 'sgg_name' => '익산시'],
            ['sido_code' => '52', 'sido_name' => '전북특별자치도', 'sgg_code' => '52740', 'sgg_name' => '장수군'],
        ];

        DB::table('sido_sgg_codes')->insert($codes);
    }
}
